from decimal import Decimal

from app.domain.models.enums import FuelType, VehicleType
from app.domain.models.vehicle import Vehicle

DEMO_VEHICLES: list[Vehicle] = [
    Vehicle(
        id="demo-crv",
        brand="Honda",
        model="CR-V",
        version="1.6 i-DTEC Executive",
        year=2016,
        vehicle_type=VehicleType.DIESEL,
        fuel_type=FuelType.DIESEL,
        purchase_price=Decimal("12000.00"),
        current_value=Decimal("5000.00"),
        annual_tax=Decimal("260.00"),
        urban_consumption=5.8,
        extraurban_consumption=4.5,
        highway_consumption=6.2,
        maintenance_cost_per_year=Decimal("750.00"),
        insurance_cost_per_year=Decimal("650.00"),
        tire_cost_per_year=Decimal("180.00"),
    ),
    Vehicle(
        id="demo-duster",
        brand="Dacia",
        model="Duster",
        version="1.5 dCi Prestige",
        year=2021,
        vehicle_type=VehicleType.DIESEL,
        fuel_type=FuelType.DIESEL,
        purchase_price=Decimal("14500.00"),
        current_value=Decimal("11000.00"),
        annual_tax=Decimal("210.00"),
        urban_consumption=5.2,
        extraurban_consumption=4.2,
        highway_consumption=5.8,
        maintenance_cost_per_year=Decimal("550.00"),
        insurance_cost_per_year=Decimal("500.00"),
        tire_cost_per_year=Decimal("140.00"),
    ),
    Vehicle(
        id="demo-zoe",
        brand="Renault",
        model="Zoe",
        version="R110 Intense 52kWh",
        year=2022,
        vehicle_type=VehicleType.BEV,
        fuel_type=FuelType.ELECTRICITY,
        purchase_price=Decimal("12900.00"),
        annual_tax=Decimal("0.00"),
        urban_consumption=13.0,
        extraurban_consumption=15.0,
        highway_consumption=20.5,
        battery_capacity=52.0,
        usable_battery_capacity=52.0,
        wltp_range=395.0,
        maintenance_cost_per_year=Decimal("220.00"),
        insurance_cost_per_year=Decimal("480.00"),
        tire_cost_per_year=Decimal("130.00"),
    ),
    Vehicle(
        id="demo-mg4",
        brand="MG",
        model="MG4",
        version="Standard 51kWh",
        year=2023,
        vehicle_type=VehicleType.BEV,
        fuel_type=FuelType.ELECTRICITY,
        purchase_price=Decimal("18500.00"),
        annual_tax=Decimal("0.00"),
        urban_consumption=14.0,
        extraurban_consumption=16.0,
        highway_consumption=21.0,
        battery_capacity=51.0,
        usable_battery_capacity=50.8,
        wltp_range=350.0,
        maintenance_cost_per_year=Decimal("200.00"),
        insurance_cost_per_year=Decimal("550.00"),
        tire_cost_per_year=Decimal("150.00"),
    ),
    Vehicle(
        id="demo-smarteq",
        brand="Smart",
        model="EQ Fortwo",
        version="passion 22kW",
        year=2021,
        vehicle_type=VehicleType.BEV,
        fuel_type=FuelType.ELECTRICITY,
        purchase_price=Decimal("11200.00"),
        annual_tax=Decimal("0.00"),
        urban_consumption=12.5,
        extraurban_consumption=14.5,
        highway_consumption=19.0,
        battery_capacity=17.6,
        usable_battery_capacity=16.7,
        wltp_range=135.0,
        maintenance_cost_per_year=Decimal("180.00"),
        insurance_cost_per_year=Decimal("400.00"),
        tire_cost_per_year=Decimal("100.00"),
    )
]
